name: Matrix Configuration

on:
  push:
  workflow_dispatch: 

jobs:
    deploy-on-ubuntu:
        strategy:
          matrix:
            os: [ubuntu-latest, ubuntu-20.04, windows-latest]
            images: [hellow-world, aplpine]
        runs-on: ${{ matrix.os }}
        steps:
          - name: Echo Docker Details
            run: docker info

          - name: Run Images on ${{ matrix.images}}
            run: docker run ${{ matrix.images 